"""Blk11_MetricSearch - Block 1.1, the metric search.

3 indices (HCPI, FCPI, CCPI) x 17 candidate fitting objectives (EM2-EM18) x 6 monthly
origins (o64-o69, Apr-Sep 2025 horizon starts) = 306 runs. Unlike every other block's
runner, the fitting metric is NOT fixed here - it is the axis under test, so it is read
per-row from Code/experiments.csv (column eval_metric) rather than hardcoded as a module
constant. This is why this block has a hand-written runner instead of one generated by
Code/common/generate_tab_runners.py (whose one-tab-one-metric template does not fit).

Reads Code/experiments.csv filtered to block == "1.1", loops every row (train through
train_data_end, forecast the horizon), skips any exp_id that already has a result sheet
(resume), writes one sheet per experiment to Results/Results_Blk11_MetricSearch.xlsx plus
a run_config.json per run under Results/RunConfigs/Blk11_MetricSearch/, and rewrites
Results/PROGRESS.md after every run.

All real logic lives in Code/common/experiment.py's run_single_experiment() - the same
function every other block's runner calls. Controls (time_limit, num_val_windows,
random_seed) are read from Code/common/config_Blk11_MetricSearch.yaml; CLI flags override.

Run: python Code/Blk11_MetricSearch/Blk11_MetricSearch.py [--exp-id <id>] [--index HCPI]
     [--force] [--time-limit 900]
"""
from __future__ import annotations

import argparse
import csv
import json
import statistics
import sys
import time
from datetime import datetime, timedelta
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from Code.common.experiment import load_tab_controls, run_single_experiment  # noqa: E402
from Code.common.results_io import (  # noqa: E402
    RESULTS_DIR,
    RUN_CONFIG_DIR,
    already_has_result,
    write_result_sheet,
    write_run_config,
)

TAB_NAME = "Blk11_MetricSearch"
BLOCK = "1.1"
EXPERIMENTS_CSV = REPO_ROOT / "Code" / "experiments.csv"
PROGRESS_PATH = RESULTS_DIR / "PROGRESS.md"

SESSION_START = time.monotonic()


def load_block_rows(index_filter: str | None = None) -> list[dict]:
    with open(EXPERIMENTS_CSV, encoding="utf-8") as f:
        rows = [r for r in csv.DictReader(f) if r["block"] == BLOCK]
    if not rows:
        raise RuntimeError(f"No rows for block {BLOCK!r} in {EXPERIMENTS_CSV}.")
    if index_filter:
        rows = [r for r in rows if r["index"] == index_filter]
    return rows


def _fmt_duration(seconds: float) -> str:
    seconds = int(seconds)
    h, rem = divmod(seconds, 3600)
    m, s = divmod(rem, 60)
    if h:
        return f"{h}h {m}m"
    if m:
        return f"{m}m {s}s"
    return f"{s}s"


def write_progress(rows: list[dict]) -> None:
    # Count completed against the same (possibly --index/--exp-id filtered) row set being
    # run, not every JSON in the directory - otherwise a per-index process reports
    # "213 / 102" and clamps the projected finish to n/a.
    wanted = {r["exp_id"] for r in rows}
    total = len(wanted)
    run_config_dir = RUN_CONFIG_DIR / TAB_NAME
    jsons = sorted(p for p in run_config_dir.glob("*.json") if p.stem in wanted) if run_config_dir.exists() else []
    records = []
    for p in jsons:
        try:
            cfg = json.loads(p.read_text(encoding="utf-8"))
        except Exception:
            continue
        records.append((p.stem, cfg.get("runtime_sec"), p.stat().st_mtime))

    completed = len(records)
    runtimes = [r for _, r, _ in records if r is not None]
    mean_rt = statistics.mean(runtimes) if runtimes else 0.0
    median_rt = statistics.median(runtimes) if runtimes else 0.0
    elapsed_sec = time.monotonic() - SESSION_START
    remaining = max(total - completed, 0)
    projected_finish = "n/a"
    if remaining and mean_rt:
        eta = datetime.now() + timedelta(seconds=remaining * mean_rt)
        projected_finish = eta.strftime("%Y-%m-%d %H:%M:%S")

    last5 = sorted(records, key=lambda r: r[2])[-5:]

    lines = [
        "# Block 1.1 - Metric Search (Blk11_MetricSearch) progress",
        "",
        f"- Block: {BLOCK}",
        f"- Completed: {completed} / {total}",
        f"- Mean runtime: {mean_rt:.1f}s" if runtimes else "- Mean runtime: n/a",
        f"- Median runtime: {median_rt:.1f}s" if runtimes else "- Median runtime: n/a",
        f"- Elapsed (this session): {_fmt_duration(elapsed_sec)}",
        f"- Projected finish: {projected_finish}",
        "",
        "## Last 5 completed runs",
        "",
        "| exp_id | runtime_sec |",
        "|---|---|",
    ]
    for exp_id, rt, _mtime in reversed(last5):
        lines.append(f"| {exp_id} | {rt if rt is not None else 'n/a'} |")
    lines.append("")
    lines.append(f"_Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}_")

    PROGRESS_PATH.parent.mkdir(parents=True, exist_ok=True)
    PROGRESS_PATH.write_text("\n".join(lines), encoding="utf-8")


def verify_run(result) -> None:
    """Soft checks per CONTROLS - printed, not fatal, so one odd run doesn't abort the
    whole 306-run block; a violation here is worth flagging but not worth losing 42 hours
    of otherwise-good runs over.
    """
    deployed = result.metadata.get("deployed_model")
    if deployed and deployed.endswith("_FULL"):
        print(f"    WARNING: {result.exp_id} deployed_model={deployed!r} - expected refit_full=False "
              "to never produce a _FULL ensemble.")
    fitted = result.run_config.get("model_pool_fitted", [])
    if not any("chronos" in m.lower() for m in fitted):
        print(f"    WARNING: {result.exp_id} - no Chronos-family model in the fitted leaderboard "
              f"(model_pool_fitted={fitted}). pretrained_models=Yes for this block.")


def main() -> None:
    controls = load_tab_controls(TAB_NAME)

    parser = argparse.ArgumentParser()
    parser.add_argument("--exp-id", default=None, help="run only this exp_id")
    parser.add_argument("--index", default=None, help='filter to one index, e.g. "HCPI"')
    parser.add_argument("--force", action="store_true", help="re-run even if a result already exists")
    parser.add_argument("--time-limit", type=int, default=controls["time_limit"])
    parser.add_argument("--num-val-windows", type=int, default=None,
                        help="override; default derives 2 per row from validation_periods/n_periods")
    parser.add_argument("--random-seed", type=int, default=controls["random_seed"])
    args = parser.parse_args()

    rows = load_block_rows(index_filter=args.index)
    if args.exp_id:
        rows = [r for r in rows if r["exp_id"] == args.exp_id]
        if not rows:
            raise SystemExit(f"exp_id {args.exp_id!r} not found in block {BLOCK} (after --index filter)")

    total = len(rows)
    workbook_path = RESULTS_DIR / f"Results_{TAB_NAME}.xlsx"
    n_run, n_skipped = 0, 0
    for row in rows:
        eval_metric_code = row["eval_metric"]
        if not args.force and already_has_result(workbook_path, row["exp_id"]):
            n_skipped += 1
            print(f"  {row['exp_id']} ({row['index']}, {eval_metric_code}): skipped (already has results)")
            continue
        print(f"  {row['exp_id']} ({row['index']}, {eval_metric_code}): running...")
        result = run_single_experiment(
            row, eval_metric_code, time_limit=args.time_limit, num_val_windows=args.num_val_windows,
            random_seed=args.random_seed, refit_full=False,
        )
        write_result_sheet(
            TAB_NAME, result.exp_id, result.metadata, result.forecast_df,
            result.weights_df, result.posthoc_df, result.release_labels,
        )
        write_run_config(TAB_NAME, result.exp_id, result.run_config)
        verify_run(result)
        n_run += 1
        print(f"  {row['exp_id']}: done in {result.runtime_sec:.1f}s "
              f"(deployed_model={result.metadata.get('deployed_model')})")
        write_progress(rows)

    print(f"\n{TAB_NAME}: {n_run} run, {n_skipped} skipped (of {total} total)")


if __name__ == "__main__":
    main()
